# Generated by Django 5.1.3 on 2024-11-17 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("e_commerce", "0002_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shippingaddress",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="order",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="shippingaddress",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="product",
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
        migrations.DeleteModel(
            name="ShippingAddress",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
