# Generated by Django 5.1.3 on 2024-11-18 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("e_commerce", "0006_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="date",
        ),
        migrations.RemoveField(
            model_name="order",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
        migrations.RemoveField(
            model_name="order",
            name="quantity",
        ),
    ]
