# Generated by Django 5.1.3 on 2024-11-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("e_commerce", "0008_remove_product_digital"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="digital",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
