# Generated by Django 5.1.3 on 2024-11-19 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("e_commerce", "0010_remove_product_digital"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="address",
            new_name="street",
        ),
    ]
