# Generated by Django 5.1.3 on 2024-11-19 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("e_commerce", "0011_rename_address_shippingaddress_street"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="street",
            new_name="address",
        ),
    ]
